name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: lint ts
        run: npm run lint:ts
        if: always()
      - name: lint scss
        run: npm run lint:scss
        if: always()
      - name: unit testing
        run: npm run test:unit
